### ISSUE TITLE
Go back link gets covered by Mobile Navbar Icon

### ISSUE THREAD

**Issue by akshatshah21** [CommunityOfCoders/COCWebsite#140] opened 2021-03-08 17:57 UTC
On nested pages that have a Go Back link, the Mobile Navbar Icon covers the arrow part:

![image](https://user-images.githubusercontent.com/47059039/110361193-b0ba8c80-8065-11eb-896e-744405a2c25d.png)

**Comment by atharvapatil123** [comment] 2022-01-15 10:14
Hi, can I work on this issue, if it's still open?

**Comment by ShubhankarKG** [comment] 2022-01-15 10:26
Sure, assigned it to you

**Comment by atharvapatil123** [comment] 2022-01-15 11:13
> ![image](https://user-images.githubusercontent.com/59118806/149619606-fbcc8410-4258-4b50-84ed-09bf93d3d167.png)

> Will this orientation of go back link work?

**Comment by akshatshah21** [comment] 2022-01-15 18:19
The problem with this is that the back link and the hamburger menu are on the same side and right next to each other. 

What if we keep them on different sides in mobile view?

**Comment by atharvapatil123** [comment] 2022-01-15 18:26
Ok, as the hamburger menu position is fixed on the left-side for all the pages. How abt this ?

![image](https://user-images.githubusercontent.com/59118806/149633413-63256721-e28f-47da-a6f3-e628cdc18fc3.png)

**Comment by ShubhankarKG** [comment] 2022-01-19 04:28
The Go Back seems to be misaligned in this case. Can we swap the hamburger menu and go back arrow ?

**Comment by atharvapatil123** [comment] 2022-01-19 07:36
> Hi @ShubhankarKG, You mean something like this?

![image](https://user-images.githubusercontent.com/59118806/150084184-f68d15ca-e62b-4377-b7b7-bb04e462ce4d.png)



> Or should I remove the hamburger option for these pages only?

![image](https://user-images.githubusercontent.com/59118806/150085134-2fcec8f7-5e6a-49a7-b0de-f87eb357b88f.png)

**Comment by ShubhankarKG** [comment] 2022-01-19 08:03
The first one looks better

**Comment by atharvapatil123** [comment] 2022-01-19 09:04
Ok @ShubhankarKG, I'll implement that one then.

**Comment by ShubhankarKG** [comment] 2022-02-15 05:18
@atharvapatil123 are you still working on this ?

**Comment by atharvapatil123** [comment] 2022-02-16 18:31
I had made a PR. Mistakenly pushed a Regression folder earlier, however deleted it later.

**Closed** 2022-02-18 14:52 UTC
Labels: good first issue
